#ifndef __ACEPINS_H
#define __ACEPINS_H

#include <stdint.h>
#include "stm32f0xx.h"


// From http://we.easyelectronics.ru/STM32/udobnaya-nastroyka-gpio-portov.html

#define GPIO_MODE_INPUT         (0x0   )
#define GPIO_MODE_OUTPUT        (0x1   )
#define GPIO_MODE_AF 						(0x2   )
#define GPIO_MODE_ANALOG 				(0x3   )

#define GPIO_OUTPUT_PUSH_PULL 	(0x0<<6)
#define GPIO_OUTPUT_OPEN_DRAIN 	(0x1<<6)

#define GPIO_SPEED_LOW 					(0x0<<2)
#define GPIO_SPEED_MEDIUM 			(0x1<<2)
#define GPIO_SPEED_HIGH 				(0x3<<2)

#define GPIO_PULL_NO 						(0x0<<4)
#define GPIO_PULL_UP 						(0x1<<4)
#define GPIO_PULL_DOWN 					(0x2<<4)

#define GPIO_MODE_INPUT_ANALOG                          (GPIO_MODE_ANALOG)
#define GPIO_MODE_INPUT_FLOATING                        (GPIO_MODE_INPUT)
#define GPIO_MODE_INPUT_PULL_UP                         (GPIO_MODE_INPUT + GPIO_PULL_UP)
#define GPIO_MODE_INPUT_PULL_DOWN                       (GPIO_MODE_INPUT + GPIO_PULL_DOWN)

#define GPIO_MODE_OUTPUT_PUSH_PULL_LOW                  (GPIO_MODE_OUTPUT + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_NO + GPIO_SPEED_LOW)
#define GPIO_MODE_OUTPUT_PUSH_PULL_UP_LOW               (GPIO_MODE_OUTPUT + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_UP + GPIO_SPEED_LOW)
#define GPIO_MODE_OUTPUT_PUSH_PULL_DOWN_LOW             (GPIO_MODE_OUTPUT + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_DOWN + GPIO_SPEED_LOW)
#define GPIO_MODE_OUTPUT_OPEN_DRAIN_LOW                 (GPIO_MODE_OUTPUT + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_NO + GPIO_SPEED_LOW)
#define GPIO_MODE_OUTPUT_OPEN_DRAIN_UP_LOW              (GPIO_MODE_OUTPUT + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_UP + GPIO_SPEED_LOW)
#define GPIO_MODE_OUTPUT_OPEN_DRAIN_DOWN_LOW            (GPIO_MODE_OUTPUT + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_DOWN + GPIO_SPEED_LOW)

#define GPIO_MODE_OUTPUT_PUSH_PULL_MEDIUM               (GPIO_MODE_OUTPUT + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_NO + GPIO_SPEED_MEDIUM)
#define GPIO_MODE_OUTPUT_PUSH_PULL_UP_MEDIUM            (GPIO_MODE_OUTPUT + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_UP + GPIO_SPEED_MEDIUM)
#define GPIO_MODE_OUTPUT_PUSH_PULL_DOWN_MEDIUM          (GPIO_MODE_OUTPUT + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_DOWN + GPIO_SPEED_MEDIUM)
#define GPIO_MODE_OUTPUT_OPEN_DRAIN_MEDIUM              (GPIO_MODE_OUTPUT + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_NO + GPIO_SPEED_MEDIUM)
#define GPIO_MODE_OUTPUT_OPEN_DRAIN_UP_MEDIUM           (GPIO_MODE_OUTPUT + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_UP + GPIO_SPEED_MEDIUM)
#define GPIO_MODE_OUTPUT_OPEN_DRAIN_DOWN_MEDIUM         (GPIO_MODE_OUTPUT + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_DOWN + GPIO_SPEED_MEDIUM)

#define GPIO_MODE_OUTPUT_PUSH_PULL_HIGH                 (GPIO_MODE_OUTPUT + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_NO + GPIO_SPEED_HIGH)
#define GPIO_MODE_OUTPUT_PUSH_PULL_UP_HIGH              (GPIO_MODE_OUTPUT + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_UP + GPIO_SPEED_HIGH)
#define GPIO_MODE_OUTPUT_PUSH_PULL_DOWN_HIGH            (GPIO_MODE_OUTPUT + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_DOWN + GPIO_SPEED_HIGH)
#define GPIO_MODE_OUTPUT_OPEN_DRAIN_HIGH                (GPIO_MODE_OUTPUT + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_NO + GPIO_SPEED_HIGH)
#define GPIO_MODE_OUTPUT_OPEN_DRAIN_UP_HIGH             (GPIO_MODE_OUTPUT + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_UP + GPIO_SPEED_HIGH)
#define GPIO_MODE_OUTPUT_OPEN_DRAIN_DOWN_HIGH           (GPIO_MODE_OUTPUT + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_DOWN + GPIO_SPEED_HIGH)

#define GPIO_MODE_AF_PUSH_PULL_LOW                      (GPIO_MODE_AF + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_NO + GPIO_SPEED_LOW)
#define GPIO_MODE_AF_PUSH_PULL_UP_LOW                   (GPIO_MODE_AF + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_UP + GPIO_SPEED_LOW)
#define GPIO_MODE_AF_PUSH_PULL_DOWN_LOW                 (GPIO_MODE_AF + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_DOWN + GPIO_SPEED_LOW)
#define GPIO_MODE_AF_OPEN_DRAIN_LOW                     (GPIO_MODE_AF + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_NO + GPIO_SPEED_LOW)
#define GPIO_MODE_AF_OPEN_DRAIN_UP_LOW                  (GPIO_MODE_AF + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_UP + GPIO_SPEED_LOW)
#define GPIO_MODE_AF_OPEN_DRAIN_DOWN_LOW                (GPIO_MODE_AF + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_DOWN + GPIO_SPEED_LOW)

#define GPIO_MODE_AF_PUSH_PULL_MEDIUM                   (GPIO_MODE_AF + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_NO + GPIO_SPEED_MEDIUM)
#define GPIO_MODE_AF_PUSH_PULL_UP_MEDIUM                (GPIO_MODE_AF + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_UP + GPIO_SPEED_MEDIUM)
#define GPIO_MODE_AF_PUSH_PULL_DOWN_MEDIUM              (GPIO_MODE_AF + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_DOWN + GPIO_SPEED_MEDIUM)
#define GPIO_MODE_AF_OPEN_DRAIN_MEDIUM                  (GPIO_MODE_AF + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_NO + GPIO_SPEED_MEDIUM)
#define GPIO_MODE_AF_OPEN_DRAIN_UP_MEDIUM           		(GPIO_MODE_AF + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_UP + GPIO_SPEED_MEDIUM)
#define GPIO_MODE_AF_OPEN_DRAIN_DOWN_MEDIUM         		(GPIO_MODE_AF + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_DOWN + GPIO_SPEED_MEDIUM)

#define GPIO_MODE_AF_PUSH_PULL_HIGH                 		(GPIO_MODE_AF + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_NO + GPIO_SPEED_HIGH)
#define GPIO_MODE_AF_PUSH_PULL_UP_HIGH         		     	(GPIO_MODE_AF + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_UP + GPIO_SPEED_HIGH)
#define GPIO_MODE_AF_PUSH_PULL_DOWN_HIGH         		   	(GPIO_MODE_AF + GPIO_OUTPUT_PUSH_PULL + GPIO_PULL_DOWN + GPIO_SPEED_HIGH)
#define GPIO_MODE_AF_OPEN_DRAIN_HIGH               		 	(GPIO_MODE_AF + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_NO + GPIO_SPEED_HIGH)
#define GPIO_MODE_AF_OPEN_DRAIN_UP_HIGH         		   	(GPIO_MODE_AF + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_UP + GPIO_SPEED_HIGH)
#define GPIO_MODE_AF_OPEN_DRAIN_DOWN_HIGH          		 	(GPIO_MODE_AF + GPIO_OUTPUT_OPEN_DRAIN + GPIO_PULL_DOWN + GPIO_SPEED_HIGH)


#define _INIT_PIN_MODER(PORT,PIN_NUM,PIN_MODE)    PORT->MODER   = (PORT->MODER   &(~((uint32_t)0x03<<(((PIN_NUM) & 0x0F)<<1)))) | (((uint32_t)(PIN_MODE)&0x03)<<(((PIN_NUM) & 0x0F)<<1))
#define _INIT_PIN_OTYPE(PORT,PIN_NUM,PIN_MODE)    PORT->OTYPER  = (PORT->OTYPER  &(~((uint32_t)0x01<<(((PIN_NUM) & 0x0F)   )))) | (((uint32_t)(PIN_MODE)&0x01)<<(((PIN_NUM) & 0x0F)   ))
#define _INIT_PIN_SPEED(PORT,PIN_NUM,PIN_MODE)    PORT->OSPEEDR = (PORT->OSPEEDR &(~((uint32_t)0x03<<(((PIN_NUM) & 0x0F)<<1)))) | (((uint32_t)(PIN_MODE)&0x03)<<(((PIN_NUM) & 0x0F)<<1))
#define _INIT_PIN_PUPDR(PORT,PIN_NUM,PIN_MODE)    PORT->PUPDR   = (PORT->PUPDR   &(~((uint32_t)0x03<<(((PIN_NUM) & 0x0F)<<1)))) | (((uint32_t)(PIN_MODE)&0x03)<<(((PIN_NUM) & 0x0F)<<1))

#define _INIT_AF(PORT,PIN_NUM,ALTFUNC) PORT->AFR[PIN_NUM / 8] = (PORT->AFR[PIN_NUM / 8] & ~(0x0FUL << ((PIN_NUM & 0x7) * 4))) \
	| ((ALTFUNC) << (PIN_NUM & 0x7) * 4);

#define _INIT_PIN(PORT,PIN_NUM,PIN_MODE)    do { _INIT_PIN_PUPDR(PORT,PIN_NUM,(PIN_MODE)>>4); \
																						     _INIT_PIN_OTYPE(PORT,PIN_NUM,(PIN_MODE)>>6); \
                                                 _INIT_PIN_SPEED(PORT,PIN_NUM,(PIN_MODE)>>2); \
																								 _INIT_PIN_MODER(PORT,PIN_NUM,(PIN_MODE)   ); } while(0);

#define GPIO_INIT_PIN(PORT_PIN_NUM,PIN_MODE)    _INIT_PIN(PORT_PIN_NUM,PIN_MODE)
//Example: GPIO_INIT_PIN(GPIOA, 3, GPIO_MODE_INPUT_PULL_DOWN);
#define GPIO_INIT_AF(PORT_PIN_NUM,ALTFUNC) _INIT_AF(PORT_PIN_NUM,ALTFUNC)


// http://we.easyelectronics.ru/STM32/udobnaya-nastroyka-gpio-stm32f030-moy-velosiped.html
#define _GPIO_SET(GPIO_PORT,GPIO_PIN) (GPIO_PORT->BSRR = (1 << GPIO_PIN))
#define _GPIO_RESET(GPIO_PORT,GPIO_PIN) (GPIO_PORT->BRR = (1 << GPIO_PIN))
#define _GPIO_TOGGLE(GPIO_PORT,GPIO_PIN) (GPIO_PORT->BSRR = (1 << (GPIO_PIN+ ((GPIO_PORT->ODR & (1 << GPIO_PIN))?16:0))))
#define _GPIO_ISSET(GPIO_PORT,GPIO_PIN) (GPIO_PORT->IDR & (1 << GPIO_PIN))
#define _GPIO_ISRESET(GPIO_PORT,GPIO_PIN) (!(GPIO_PORT->IDR & (1 << GPIO_PIN)))

#define GPIO_SET(PORT_PIN_NUM) _GPIO_SET(PORT_PIN_NUM)
#define GPIO_RESET(PORT_PIN_NUM) _GPIO_RESET(PORT_PIN_NUM)
#define GPIO_TOGGLE(PORT_PIN_NUM) _GPIO_TOGGLE(PORT_PIN_NUM)
#define GPIO_ISSET(PORT_PIN_NUM) _GPIO_ISSET(PORT_PIN_NUM)
#define GPIO_ISRESET(PORT_PIN_NUM) _GPIO_ISRESET(PORT_PIN_NUM)

#ifndef GPIO_AF_0
 #define GPIO_AF_0 ((uint8_t)0x00)
 #define GPIO_AF_1 ((uint8_t)0x01)
 #define GPIO_AF_2 ((uint8_t)0x02)
 #define GPIO_AF_3 ((uint8_t)0x03)
 #define GPIO_AF_4 ((uint8_t)0x04)
 #define GPIO_AF_5 ((uint8_t)0x05)
 #define GPIO_AF_6 ((uint8_t)0x06)
 #define GPIO_AF_7 ((uint8_t)0x07)
#endif

void DisableJTAG(void);

#endif
